name: flutter_supabase_enterprise_crud
description: Enterprise-style Flutter CRUD app with Supabase
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ">=3.41.0 <3.42.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
